name: review_dashboard_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.2.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/oriflame_banner.png
    - assets/menu_icons/Nav Bar Icons.svg
    - assets/menu_icons/Shared_content.svg
    - assets/menu_icons/Member.svg
    - assets/menu_icons/Library_asset.svg
    - assets/menu_icons/Education_hub.svg
    - assets/menu_icons/Campaigns.svg
    - assets/menu_icons/Communities.svg
    - assets/menu_icons/Hashtags.svg
    - assets/menu_icons/AI_console.svg
    - assets/menu_icons/second/Review_accounts.svg
    - assets/menu_icons/second/push_notification.svg
    - assets/menu_icons/second/sharing_control.svg
    - assets/menu_icons/second/user_management.svg
    - assets/menu_icons/second/Appearance.svg
    - assets/menu_icons/second/FAQ.svg
    - assets/menu_icons/Sign out.svg
    - assets/social_media_icons/Instagram.svg
    - assets/social_media_icons/Facebook.svg
    - assets/social_media_icons/Tik Tok.svg
    - assets/social_media_icons/Whatsapp.svg
    - assets/profile/Brand.svg
    - assets/profile/pofile.png
    - assets/menu_icons/brandie.svg
    - assets/UK_flag.png
    - assets/profile/id_imag.png
# assets:
# - assets/oriflame_banner.png
#   - images/a_dot_ham.jpeg

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/to/asset-from-package

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Satoshi
#     fonts:
#       - assets/fonts/Satoshi-Variable.ttf
#       - assets/fonts/Satoshi-VariableItalic.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package
